
ANSWERS_3 = {
    161: "B. plt.subplots(2, 2) creates a 2x2 grid...",
    162: "C. plt.plot(df[\"age\"]) creates a line plot... (Or histogram via .hist?)",
    163: "C. It prevents dependency conflicts...",
    164: "C. Dynamically typed, interpreted, high-level", 
    165: "B. Web development, machine learning, automation",
    166: "D. Type conversion",
    167: "C. for loop",
    168: "C. palindrome is a string that reads the same... s == s[::-1]",
    169: "C. math.pi : provides the constant value of pi",
    170: "D. Use continue inside the loop...", # Wait, question was "stop" infinite loop? A: add i+=1 fixes it. D: continue makes it skipping? No, A fixes the infinite loop by progressing.
    171: "B. split() : breaks a string into a list...",
    172: "A. Inheritance : Dog reuses...",
    173: "B. Turn Payment into an abstract base class...",
    174: "C. super().__init__() : invokes the parent class's initializer",
    175: "B. It initializes object attributes...",
    176: "C. Pandas",
    177: "A. python -m venv env",
    178: "D. Assigning df[\"col\"] = ... updates",
    179: "B. pd.merge(df1, df2, on=\"id\")",
    180: "A. plt.title(\"Sales Data\")",
    181: "C. plt.barh(x, y)", 
    182: "A. df = pd.read_csv(\"data.csv\"); print(df.head())",
    183: "A. input()",
    184: "B. bool",
    185: "D. indentation", # Correct answer for defining block "structurally".
    186: "C. HelloHello",
    187: "D. **",
    188: "B. 5",
    189: "C. No output (5 > 5 is False)",
    190: "C. Sends a value back from a function", 
    191: "D. min()",
    192: "C. from module import function",
    193: "B. 2.0 (10/5)",
    194: "C. Set",
    195: "B. They are immutable",
    196: "D. 5",
    197: "B. Polymorphism",
    198: "C. lambda",
    199: "B. Numerical computations and arrays",
    200: "C. pd.read_csv()",
    201: "A. plt.bar()",
    202: "B. Dropping duplicate rows", 
    203: "C. python --version",
    204: "D. yth", # s[1:4] -> indices 1,2,3 -> y,t,h
    205: "B. float",
    206: "B. **",
    207: "A. True (not(False) and True -> True and True -> True)",
    208: "C. s = set()",
    209: "B. [1, 2, 3, 4] (List is mutable, passed by reference)",
    210: "C. open(\"file.txt\", \"w+\") (Overwrites)",
    211: "B. 14 (2+3 + sum(4,5) -> 5+9=14)", 
    212: "D. include math",
    213: "B. [3 4 5] (Row index 1)", 
    214: "B. df.describe()",
    215: "C. Histogram", 
    216: "C. int()",
    217: "B. No (x is None)",
    218: "C. yield",
    219: "A. Hiding internal state...",
    220: "A. {'a':1, 'b':2}",
    221: "C. A random integer between 1 and 5 inclusive",
    222: "B. plt.plot([1,2,3], [4,5,6])",
    223: "C. Low-level memory management",
    224: "B. 3 (10 // 3)",
    225: "B. value_1", 
    226: "C. str",
    227: "A. False (True and not False -> True and True -> True). Wait... a=True, b=False. a and not b => True and True => True. Options say False/True. Answer is True. B.",
    228: "B. for loop",
    229: "B. 2 5 8 (start 2, step 3)", 
    230: "C. 6 (3 * default 2)",
    231: "B. max()",
    232: "B. from math import sqrt",
    233: "C. Error (ZeroDivisionException caught)",
    234: "C. Set",
    235: "C. 3",
    236: "B. Inheritance",
    237: "C. A (A.show not overridden)",
    238: "B. Create anonymous functions", 
    239: "C. (2, 2)", 
    240: "B. DataFrame",
    241: "B. Draws a line graph" # Correct
}
