
# Auto-generated answers by AI
ANSWERS = {
    1: "c) .py",
    2: "b) <class 'int'>",
    3: "d) def",
    4: "c) pip install package-name",
    5: "a) 4 (The list has 4 elements: 1, 2, 3, and list [4,5])",
    6: "c) Set",
    7: "c) {1:'b'} (Keys must be unique, second assignment overwrites)", 
    8: "b) They allow reusability of code",
    9: "d) Encapsulation",
    10: "a) __init__()",
    11: "c) open(\"file.txt\", \"w\")",
    12: "d) anonymous functions",
    13: "a) Modifies the functionality of a function",
    14: "a) yield",
    15: "b) python3 -m venv env",
    16: "d) Support vectorized operations",
    17: "b) np.array()",
    18: "b) DataFrame",
    19: "c) pd.read_csv()",
    20: "b) plt.plot()",
    # Second block (1-20 again)
    21: "b) python --version", # checking installed version
    22: "c) _value2", # valid variable name start with _ or letter
    23: "b) //",
    24: "c) Does nothing; acts as a placeholder",
    25: "a) List",
    26: "b) A tuple with one element",
    27: "b) add()",
    28: "b) random",
    29: "b) Methods",
    30: "d) class Child(Parent)",
    31: "c) a+", # read and write without erasing (append mode + read) - actually r+ is read/write without truncate? a+ appends. The options are tricky. r+ reads/writes without erasing but pointer at start. a+ pointer at end. Given options, a+ preserves content.
    32: "b) @",
    33: "b) They produce values on demand",
    34: "c) They are defined using the lambda keyword",
    35: "b) source env/bin/activate (Standard for Linux/Mac)", 
    36: "a) np.zeros()",
    37: "c) First 5 rows",
    38: "b) shape",
    39: "a) plt.show()",
    40: "b) concat()", # Combine horizontally? concat with axis=1. merge is database style. join is index based. concat is most generic.
    # Third block
    41: "d) arraylist", # Not valid in Python (Java thing)
    42: "c) input()",
    43: "c) 9",
    44: "c) both for and while (Python loops have else clauses)",
    45: "b) range object", 
    46: "b) insert()",
    47: "a) {}",
    48: "b) from module import function",
    49: "c) class",
    50: "c) recursive function",
    51: "b) x (Exclusive creation mode)",
    52: "c) len()",
    53: "d) except",
    54: "b) Applies a function to each item of an iterable",
    55: "c) yield",
    56: "b) pip install numpy",
    57: "b) dropna()", 
    58: "b) ndim",
    59: "b) plt.title()",
    60: "a) pd.read_excel()",
    # Fourth block
    61: "b) break",
    62: "c) None",
    63: "b) is",
    64: "b) class Student():",
    65: "a) iter()",
    66: "c) tuples (Keys must be immutable)",
    67: "b) To ensure files are closed automatically",
    68: "c) IndexError", 
    69: "b) Pairs elements from iterables into tuples",
    70: "a) reduce() (functools.reduce)",
    71: "d) init.py (__init__.py)",
    72: "a) pip list",
    73: "b) evenly spaced values",
    74: "b) merge()", 
    75: "a) Data type of array elements",
    76: "b) Summary statistics",
    77: "a) plt.bar()",
    78: "c) lambda",
    79: "c) They can grow or shrink dynamically",
    80: "c) id()" 
} # Truncated for first batch write
