
ANSWERS_2 = {
    81: "b) #",
    82: "c) abs()",
    83: "b) list", 
    84: "c) skips the current iteration",
    85: "b) float (True in Python 3)",
    86: "b) removes and returns the last element",
    87: "b) keys()",
    88: "c) math",
    89: "b) an instance of a class",
    90: "c) del() (__del__ destructor)",
    91: "b) handling runtime errors gracefully",
    92: "b) generator/iterator (filter object in Py3)",
    93: "c) a function",
    94: "a) deactivate",
    95: "a) np.eye()",
    96: "b) df.tail()",
    97: "b) size of each element in bytes",
    98: "a) plt.xlabel()",
    99: "c) df.to_csv()",
    100: "a) dir()",
    101: "d) indent (Python uses indentation, but : starts it. Strictly, indentation checks block)", 
    102: "a) int()",
    103: "b) **",
    104: "b) data type of an object",
    105: "b) remove()",
    106: "c) list-like view of values (dict_values object)",
    107: "b) datetime",
    108: "c) call parent class methods",
    109: "c) CompileError (Python has SyntaxError, but CompileError isn't standard built-in exception name exposed commonly)",
    110: "b) generator",
    111: "b) @classmethod",
    112: "d) pip install --upgrade package",
    113: "c) equally spaced values", 
    114: "c) size",
    115: "b) memory usage and column types",
    116: "c) line plot", 
    117: "b) df.rename()",
    118: "b) else (Used in loops/try for 'if no break/exception')",
    119: "c) current object instance",
    120: "b) next()",
    121: "C. Yes, but Python variables act as references...",
    122: "D. sep and end",
    123: "B. A British comedy group known for sketch comedy (Monty Python)",
    124: "B. Declaration specifies type... (Actually Python doesn't have strict declaration vs definition separation like C. But D implies assignment creates reference which is true behavior)",
    125: "B. nums = list(map(int, [\"1\",\"2\",\"3\"]))",
    126: "A. while loop",
    127: "B. User-created .py files...",
    128: "C. raise ValueError(\"Invalid input\")",
    129: "A. It allows you to handle runtime errors...",
    130: "D. It refers to the current object instance...",
    131: "A. Object-oriented programming...",
    132: "C. Make balance a private attribute...",
    133: "C. Standard deviation measures data variability...",
    134: "A. Performing array operations without explicit Python loops...",
    135: "D. Because NumPy uses optimized C-based arrays...",
    136: "C. [[1, 2, 3], [4, 5, 6]]", 
    137: "B. It prints a blank line",
    138: "C. df[\"date\"] = pd.to_datetime(df[\"date\"])",
    139: "B. plt.savefig(\"output.png\")", 
    140: "D. plt.scatter(x, y); plt.plot(x, y_pred)",
    141: "D. print(0o010) - Wait, 008 is invalid octal. 0o10 only works for 8. To print 8? print(int('008')) works if string. Question logic is messy. C: print(int(0o10)) -> print(int(8)) -> 8. But 0o10 is Octal 8. 008 is SyntaxError in Py3. Assuming C is the intended 'trick'.",
    142: "D. A multi-paradigm approach...",
    143: "B. Python's built-in package manager...",
    144: "A. random.randint(1, 10)... (Correct usage)",
    145: "C. Arithmetic operators perform mathematical calculations...",
    146: "D. x = 10; x = \"hello\" (Reassigning type)",
    147: "C. len() : returns the number of elements...",
    148: "D. random.randint() : generates a random integer", 
    149: "C. Remove or disable the update (i += 1)...",
    150: "C. Lambdas are small anonymous functions...",
    151: "D. Use classes and objects...",
    152: "C. Allow each subclass to provide its own implementation...",
    153: "D. normal .... around a mean ... uniform ... flat range",
    154: "A. arr = arr.fillna(np.mean(arr)) (Pandas) / C for basic replacement logic",
    155: "C. clean = arr.dropna() (Pandas)",
    156: "C. A transpose flips rows and columns; arr.T",
    157: "A. No, NumPy also includes linear algebra...",
    158: "C. A 1D labeled array capable of holding any data type",
    159: "A. df.loc[\"A\":\"C\"] selects rows from label A to C", 
    160: "D. plt.scatter(x, y)"
}
